### ISSUE TITLE
excel export multi-sheet bug

### ISSUE THREAD

**Issue by addwoods** [hs-web/hsweb-expands#1]
i run a test of  org.hsweb.expands.office.excel.TestWriter.testWriteCustomStyle, 
i got some errors.  the detail: 
17:38:09.983 [main] ERROR o.h.e.o.e.a.p.c.CommonExcelWriterCallBack - writer processor error!
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@41d477ed
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:502) ~[poi-ooxml-3.14.jar:3.14]
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1467) ~[poi-ooxml-3.14.jar:3.14]
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:217) ~[poi-ooxml-3.14.jar:3.14]
	at org.hsweb.expands.office.excel.api.poi.callback.POIExcelWriterProcessor.done(POIExcelWriterProcessor.java:100) ~[classes/:na]
	at org.hsweb.expands.office.excel.api.poi.callback.CommonExcelWriterCallBack.render(CommonExcelWriterCallBack.java:51) ~[classes/:na]
	at org.hsweb.expands.office.excel.api.poi.POIExcelApi.write(POIExcelApi.java:117) [classes/:na]
	at org.hsweb.expands.office.excel.support.CommonExcelWriter.write(CommonExcelWriter.java:33) [classes/:na]
	at org.hsweb.expands.office.excel.ExcelIO.write(ExcelIO.java:143) [classes/:na]
	at org.hsweb.expands.office.excel.TestWriter.testWriteCustomStyle(TestWriter.java:283) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160) [junit-4.11.jar:na]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@41d477ed
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:490) ~[poi-ooxml-3.14.jar:3.14]
	... 36 common frames omitted

i can't export the second sheet. how to resolve it ?

**Comment by zhou-hao** [comment]
bug is fixed .

**Comment by addwoods** [comment]
yes , it's work fine. but the excel file can't be opened.
btw,  my office is excel 2007.
what's version yours office?

**Comment by zhou-hao** [comment]
i'm using  [wps](http://www.wps.cn/) and [libreoffice](https://www.libreoffice.org). I will be resolved as soon as possible.
